language: generic
sudo: required
servies:
  - docker

before_install:
  - docker build -t kalan/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true kalan/docker-react npm run test -- --coverage
